name: "E2E Test - iOS"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-flutter-ios-e2e-app:
    runs-on: macos-26
    environment:
      name: Only Main
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: '26.5'

      - name: Run Xcode first launch tasks
        run: xcodebuild -runFirstLaunch

      - name: Install iOS Simulator runtime
        run: xcodebuild -downloadPlatform iOS

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager

      - name: Clean build cache
        working-directory: e2e
        run: |
          flutter clean
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Build iOS
        working-directory: e2e
        run: flutter build ios --simulator

      - name: Zip app
        working-directory: e2e
        run: |
          cd build/ios/iphonesimulator && zip -r Runner.app.zip ./Runner.app

      - name: Upload to MagicPod
        working-directory: e2e
        run: |
          curl --fail-with-body -L -X POST \
            -F "file=@build/ios/iphonesimulator/Runner.app.zip" \
            -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" \
            "https://app.magicpod.com/api/v1.0/Nubrick.app/Nubrick-Flutter/upload-file/"
