name: "E2E Test - Android"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-android-e2e-app:
    runs-on: ubuntu-latest
    environment:
      name: Only Main
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Build Android
        working-directory: e2e
        run: flutter build apk --debug

      - name: Upload e2e app
        working-directory: e2e
        run: |
          curl --fail-with-body -L -X POST \
            -F "file=@build/app/outputs/flutter-apk/app-debug.apk" \
            -H "Authorization: Token ${{ secrets.MAGICPOD_API_TOKEN }}" \
            "https://app.magicpod.com/api/v1.0/Nubrick.app/Nubrick-Flutter/upload-file/"
